name: ngmaster
description: Multi-antigen sequence typing for _Neisseria gonorrhoeae_
icon: false
tags:
  - fasta
  - Neisseria gonorrhoeae
  - serotype
modules:
  - ngmaster
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Neisseria gonorrhoeae fasta file.
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample ngmaster result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all ngmaster result files
      pattern: "ngmaster.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
docs:
  meta:
    title: ngmaster
    description: >-
      A braseqtb Tool which uses ngmaster for _in silico_ multi-antigen sequence
      typing for _Neisseria gonorrhoeae_ (NG-MAST).
  introduction: |
    The `ngmaster` module uses [ngmaster](https://github.com/MDU-PHL/ngmaster) for 
    _in silico_ multi-antigen sequence typing for _Neisseria gonorrhoeae_ (NG-MAST).
  output:
    tree: |
      <braseqtb_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── ngmaster
      │           ├── <SAMPLE_NAME>.tsv
      │           └── logs
      │               ├── nf-ngmaster.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── braseqtb-runs
          └── ngmaster-<TIMESTAMP>
              ├── merged-results
              │   ├── logs
              │   │   └── ngmaster-concat
              │   │       ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │   │       └── versions.yml
              │   └── ngmaster.tsv
              └── nf-reports
                  ├── ngmaster-dag.dot
                  ├── ngmaster-report.html
                  ├── ngmaster-timeline.html
                  └── ngmaster-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: ngmaster.tsv
            description: A merged TSV file with `ngmaster` results from all samples
      - name: ngmaster
        description: |
          Below is a description of the _per-sample_ results from [ngmaster](https://github.com/MDU-PHL/ngmaster).
        table:
          - id: <SAMPLE_NAME>.tsv
            description: A tab-delimited file with `ngmaster` results
  citations:
    - csvtk
    - ngmaster
