name: emmtyper
description: emm-typing of _Streptococcus pyogenes_ assemblies
icon: false
tags:
  - fasta
  - Streptococcus pyogenes
  - typing
modules:
  - emmtyper
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Streptococcus pyogenes fasta file.
      pattern: "*.{fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample emmtyper result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all emmtyper result files
      pattern: "emmtyper.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
docs:
  meta:
    title: emmtyper
    description: >-
      A braseqtb Tool which uses emmtyper for emm-typing of _Streptococcus pyogenes_
      using a de novo or complete assembly.
  introduction: |
    The `emmtyper` module uses [emmtyper](https://github.com/MDU-PHL/emmtyper) for 
    emm-typing of _Streptococcus pyogenes_ using a de novo or complete assembly.
  output:
    tree: |
      <braseqtb_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── emmtyper
      │           ├── <SAMPLE_NAME>.tsv
      │           └── logs
      │               ├── nf-emmtyper.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── braseqtb-runs
          └── emmtyper-<TIMESTAMP>
              ├── merged-results
              │   ├── emmtyper.tsv
              │   └── logs
              │       └── emmtyper-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── emmtyper-dag.dot
                  ├── emmtyper-report.html
                  ├── emmtyper-timeline.html
                  └── emmtyper-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: emmtyper.tsv
            description: A merged TSV file with `emmtyper` results from all samples
      - name: emmtyper
        description: |
          Below is a description of the _per-sample_ results from [emmtyper](https://github.com/MDU-PHL/emmtyper).
        table:
          - id: <SAMPLE_NAME>.tsv
            description: A tab-delimited file with `emmtyper` result, see [emmtyper - Result format](https://github.com/MDU-PHL/emmtyper#result-format) for details
  citations:
    - csvtk
    - emmtyper
