name: pneumocat
description: Assign capsular type to Streptococcus pneumoniae from sequence reads
icon: false
keywords:
  - TAGS
modules:
  - LIST_OF_MODULES
input:
  - meta:
    type: map
    description: |
      Groovy Map containing sample information
      e.g. [ id:'test', single_end:false ]
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
docs:
  meta:
    title: pneumocat
    description: >
      A braseqtb Tool which uses PneumoCaT to assign capsular type to _Streptococcus pneumoniae_ from sequence reads.
  introduction: |
      The `pneumocat` module uses [PneumoCaT](https://github.com/ukhsa-collaboration/PneumoCaT) to assign capsular
      type to _Streptococcus pneumoniae_ from sequence reads.
  output:
    tree: |
      <braseqtb_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── pneumocat
      │           ├── <SAMPLE_NAME>.results.xml
      │           ├── coverage_summary.txt
      │           └── logs
      │               ├── nf-pneumocat.{begin,err,log,out,run,sh,trace}
      |               ├── pneumo_capsular_typing.std{err|out}
      │               └── versions.yml
      └── braseqtb-runs
          └── pneumocat-<TIMESTAMP>
              └── nf-reports
                  ├── pneumocat-dag.dot
                  ├── pneumocat-report.html
                  ├── pneumocat-timeline.html
                  └── pneumocat-trace.txt
    add_note: false
    folders:
      - name: PneumoCaT
        description: |
          Below is a description of the _per-sample_ results from [PneumoCaT](https://github.com/ukhsa-collaboration/PneumoCaT).
        table:
          - id: <SAMPLE_NAME>.results.xml
            description: An XML that details the final assigned capsular type
          - id: coverage_summary.txt
            description: A summary of the coverage for each capsular type
  citations:
    - pneumocat
