name: iqtree
description: Phylogeny from a multiple sequence alignment using the maxium likelihood algorithm
introduction: |
  The `iqtree` module uses [IQ-TREE](https://github.com/Cibiv/IQ-TREE) to create phylogenetic trees
  based on a multiple sequence alignment. In most cases the `iqtree` module will be used in a 
  subworkflow where an alignment is created.
tags:
  - alignment
  - phylogeny
modules:
  - iqtree
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - alignment:
      type: file
      description: A FASTA format multiple sequence alignment file
      pattern: "*.{fasta,fas,fa,mfa,aln,aln.gz}"
output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - phylogeny:
      type: file
      description: A phylogeny in Newick format
      pattern: "*.{treefile}"
citations:
  - iqtree
  - iqtree_modelfinder
  - iqtree_ufboot
