name: gtdbtk_setupdb
description: GTDB-Tk is a software toolkit for assigning objective taxonomic classifications to bacterial and archaeal genomes based on the Genome Database Taxonomy GTDB.
keywords:
  - GTDB taxonomy
  - taxonomic classification
tools:
  - gtdbtk:
      description: GTDB-Tk is a software toolkit for assigning objective taxonomic classifications to bacterial and archaeal genomes based on the Genome Database Taxonomy GTDB.
      homepage: https://ecogenomics.github.io/GTDBTk/
      documentation: https://ecogenomics.github.io/GTDBTk/
      tool_dev_url: https://github.com/Ecogenomics/GTDBTk
      doi: "10.1093/bioinformatics/btz848"
      licence: ['GNU General Public v3 (GPL v3)']

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - setup:
      type: file
      description: An empty file confirming the database was setup
      pattern: "gtdb-setup.txt"
authors:
  - "@skrakau"
  - "@abhi18av"
