name: agrvate
description: Rapid identification of Staphylococcus aureus agr locus type and agr operon variants.
icon: false
tags:
  - fasta
  - virulence
  - Staphylococcus aureus
modules:
  - agrvate
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Staphylococcus aureus fasta file.
      pattern: "*.fasta"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: Per-sample summary of the agrvate assessement
      pattern: "*-summary.tab"
  - merged_tsv:
      type: file
      description: A merged summary of the agrvate assessement
      pattern: "agrvate.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
docs:
  meta:
    title: argvate
    description: >-
      A braseqtb Tool which uses AgrVATE to rapidly identify the _agr_ locus
      type in _Staphylococcus aureus_ assemblies.
  introduction: |
      The `agrvate` module uses [AgrVATE](https://github.com/VishnuRaghuram94/AgrVATE) 
      to rapidly identify the _agr_ locus type in _Staphylococcus aureus_ assemblies.
  output:
    tree: |
      <braseqtb_DIR>
      ├── <SAMPLE_NAME>
      │   └── tools
      │       └── agrvate
      │           ├── <SAMPLE_NAME>-agr_gp.tab
      │           ├── <SAMPLE_NAME>-blastn_log.txt
      │           ├── <SAMPLE_NAME>-summary.tab
      │           └── logs
      │               ├── nf-agrvate.{begin,err,log,out,run,sh,trace}
      │               └── versions.yml
      └── braseqtb-runs
          └── agrvate-<TIMESTAMP>
              ├── merged-results
              │   ├── agrvate.tsv
              │   └── logs
              │       └── agrvate-concat
              │           ├── nf-merged-results.{begin,err,log,out,run,sh,trace}
              │           └── versions.yml
              └── nf-reports
                  ├── agrvate-dag.dot
                  ├── agrvate-report.html
                  ├── agrvate-timeline.html
                  └── agrvate-trace.txt
    add_note: true
    folders:
      - name: Merged Results
        description: |
          Below are results that are concatenated into a single file.
        table:
          - id: agrvate.tsv
            description: A merged TSV file with `AgrVATE` results from all samples
      - name: AgrVATE
        description: |
          Below is a description of the _per-sample_ results from [AgrVATE](https://github.com/VishnuRaghuram94/AgrVATE).
        is_extensions: true
        table:
          - id: -agr_gp.tab
            description: A detailed report for _agr_ kmer matches
          - id: -blastn_log.txt
            description: Log files from programs called by `AgrVATE`
          - id: -summary.tab
            description: A final summary report for _agr_ typing
  citations:
    - agrvate
    - csvtk
